
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.soap;

import java.io.File;
import java.util.logging.Logger;

import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.DocumentHelper;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;

import com.type.SReturnVO;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-10-21T15:21:00.484+08:00
 * Generated source version: 2.7.15
 * 
 */

@javax.jws.WebService(
                      serviceName = "ScfMobileSoap",
                      portName = "ScfPccSoapServiceEndpointPort",
                      targetNamespace = "rm:soap",
                      endpointInterface = "com.soap.ScfPccSoapServiceEndpoint")
                      
public class ScfPccSoapServiceEndpointImpl implements ScfPccSoapServiceEndpoint {

    private static final Logger LOG = Logger.getLogger(ScfPccSoapServiceEndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see rm.soap.ScfPccSoapServiceEndpoint#notifyUserInfo(rm.type.SnotifyUserInfoParaVO  inPara )*
     */
    public com.type.SReturnVO notifyUserInfo(com.type.SnotifyUserInfoParaVO inPara) { 
        LOG.info("Executing operation notifyUserInfo");
        System.out.println(inPara);
        System.out.println("content = " + inPara.getContent());
        String result = null;
        result = dom4j(inPara.getContent());
        System.out.println(result);
        try {
//            com.type.SReturnVO _return = null;
        	 com.type.SReturnVO _return = new SReturnVO();
        	 String reslut = inPara.getContent() + " client call server";
        	 _return.setResultDesc(reslut);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public static String dom4j(String content){
    	SAXReader reader = new SAXReader();  
        // 通过read方法读取一个文件 转换成Document对象  
    	String result = null;;
    	 try {
//    		 Document document = reader.read(new File(filePath));  
			Document document = DocumentHelper.parseText(content);
			Element root = document.getRootElement(); 
			result = root.elementText("director");
			
		} catch (DocumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	 return result;
    }
    
    public static void main(String[] args) {
		String result = dom4j("C:/Users/80575749/Desktop/OnePNS/demo.xml");
		System.out.println(result);
	}
    
}


//wsdlLocation = "file:/C:/Users/80575749/Desktop/OnePNS/SoapNotification.wsdl",