
package com.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-10-21T15:21:00.640+08:00
 * Generated source version: 2.7.15
 * 
 */
 
public class ScfPccSoapServiceEndpoint_ScfPccSoapServiceEndpointPort_Server{

    protected ScfPccSoapServiceEndpoint_ScfPccSoapServiceEndpointPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ScfPccSoapServiceEndpointImpl();
        String address = "REPLACE_WITH_ACTUAL_URL";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ScfPccSoapServiceEndpoint_ScfPccSoapServiceEndpointPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
