package com.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-10-21T15:21:00.640+08:00
 * Generated source version: 2.7.15
 * 
 */
@WebService(targetNamespace = "rm:soap", name = "ScfPccSoapServiceEndpoint")
@XmlSeeAlso({com.type.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ScfPccSoapServiceEndpoint {

    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    @WebMethod
    public com.type.SReturnVO notifyUserInfo(
        @WebParam(partName = "inPara", name = "inPara")
        com.type.SnotifyUserInfoParaVO inPara
    );
}
