
package com.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-10-21T16:41:54.713+08:00
 * Generated source version: 2.7.15
 * 
 */
public final class ScfPccSoapServiceEndpoint_ScfPccSoapServiceEndpointPort_Client {

    private static final QName SERVICE_NAME = new QName("rm:soap", "ScfMobileSoap");

    private ScfPccSoapServiceEndpoint_ScfPccSoapServiceEndpointPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ScfMobileSoap.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ScfMobileSoap ss = new ScfMobileSoap(wsdlURL, SERVICE_NAME);
        ScfPccSoapServiceEndpoint port = ss.getScfPccSoapServiceEndpointPort();  
        
        {
        System.out.println("Invoking notifyUserInfo...");
        com.type.SnotifyUserInfoParaVO _notifyUserInfo_inPara = null;
        com.type.SReturnVO _notifyUserInfo__return = port.notifyUserInfo(_notifyUserInfo_inPara);
        System.out.println("notifyUserInfo.result=" + _notifyUserInfo__return);


        }

        System.exit(0);
    }

}
